### ISSUE TITLE
Notification: tts.speak incorrect validation

### ISSUE THREAD

**Issue by illuzn** [nielsfaber/alarmo#1012]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.8.0

### Bug description

As mentioned in #927, `media_player_entity_id` can be singular e.g. `media_player.speaker` or a list e.g.
```
service: tts.speak
target:
  entity_id: tts.google_en_com_au
data:
  cache: true
  media_player_entity_id: 
    - media_player.speaker1
    - media_player.speaker2
    - media_player.spekaer3
  message: This is a test
  language: en-au
```
If a single media player is provided the previous fix works. However, if a list is provided (can only be done through YAML) the validation fails stating "Required key 'media_player_entity' is missing." This is despite the fact that pressing "Try It" works and this also works in via the developer tools->actions tab.

### Steps to reproduce

Replace your media player and TTS engine entities as appropriate.

service: tts.speak
target:
  entity_id: tts.google_en_com_au
data:
  cache: true
  media_player_entity_id: 
    - media_player.speaker1
    - media_player.speaker2
    - media_player.spekaer3
  message: This is a test
  language: en-au

### Relevant log output

```shell
Not relevant
```
