### ISSUE TITLE
Delay for triggered Sensor

### ISSUE THREAD

**Issue by TheRealFalseReality** [nielsfaber/alarmo#1014]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
It would be nice to have a delay if a binary_sensor changes state to 'on'. Like triggered alarm when sensor is on for X seconds, to prevent some false alarms (pun intended). I use a Frigate Person Occupancy sensor in hopes to only trigger the alarm when the camera detects a person, but in a certain room, a jacket can give a false positive, but only for a second or 2, but Alarmo will trigger immediately. I'm am gonna use a template helper to copy this sensor with a delay so hopefully quick state changed won't trigger the alarm.

### Additional info
Now, alarm triggers as soon as sensor state is 'on'.
Requests, alarm triggers when sensor is 'on' for X seconds.

**Comment by davidtinker** [comment]
That would be a great addition. I have been trying to use the [template integration](https://www.home-assistant.io/integrations/template/#state-based-template-binary-sensors-buttons-images-numbers-selects-and-sensors) to do this but haven't got it working yet. This is what I have so far but it doesn't turn on at all:

```
template:
  - binary_sensor:
      name: 'Back person occupancy delayed'
      delay_on: 0:00:03
      state: '{{states("sensor.back_person_occupancy")}}'
      device_class: occupancy
```
