### ISSUE TITLE
Error while test/modify nofification action: "extra keys not allowed @ data['entity_id']. Got None"

### ISSUE THREAD

**Issue by hanshanderson** [nielsfaber/alarmo#1051]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.6 / v1.10.5 / v1.10.4

### HA Version

2024.10.3

### Bug description

While testing an existing notification I'm getting following error message:

`extra keys not allowed @ data['entity_id']. Got None`

YAML code of existing notification:

```
service: notify.mobile_app_all
entity_id: null
data:
  message: >-
    Der Alarm konnte im Moment nicht scharfgeschaltet werden, aufgrund von:
    {{open_sensors|lang=de}}.
  title: Alarmo - Scharfschaltung fehlgeschlagen
```
Expecting that 'entity_id: null' is the reason for this. Deleting the line and saving  creates the following error message:

```
Something went wrong!
Message format incorrect: string value is None for dictionary value @ data['actions'][0]['entity_id']

Response error: 400

Please report the bug.
```

### Steps to reproduce

1. Create a new notification and before you save it try to send test notification -> test message will be send
2. Check YAML code -> No 'entity_id: null' visible
3. Save the notification
4. Reopen saved notification and try to test sending a test message -> Error message appears
5. Check YAML code -> 'entity_id: null' is added

Additional remarks:
- Initially expecting that the issue was related to new released v1.10.6. But with rollback to v1.10.5 and v1.10.4 same behaviour.
- If the notification is triggered by alarmo itself message is send without issues.

### Relevant log output

```shell
2024-10-23 22:50:35.423 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['entity_id']
```
