### ISSUE TITLE
Error when trying to add channel and priority to notifications

### ISSUE THREAD

**Issue by javiericu** [nielsfaber/alarmo#1064]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

V1.10.6

### HA Version

2024.10.2

### Bug description

When trying to add channel and priority to a notification (for android) I get the following result

extra keys not allowed @ data['entity_id']. Got None

### Steps to reproduce

```
service: notify.mobile_app_2306epn60g
data:
  message: "¡Se ha disparado la alarma! Causa: {{open_sensors}}."
  title: "Uu"
  data:
    channel: alarm_stream
    priority: high
```
