### ISSUE TITLE
Using information about HA User to automatically arm or disarm

### ISSUE THREAD

**Issue by AzraelsDisk** [nielsfaber/alarmo#1112]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Using information about HA User for interaction

### Additional info
All HA Users are not at home --> ARM
At least one User is coming --> disarm

**Comment by Trexano99** [comment]
Use can achieve this easily with 2 automations.
1. **Arm home when leaving**:
```yaml
mode: single
triggers:
  - trigger: state
    entity_id:
      - person.userOne
      - person.userTwo
    to: not_home
conditions:
  - condition: state
    entity_id:
      - person.userOne
      - person.userTwo
    state: not_home
actions:
  - action: alarm_control_panel.alarm_arm_away
    data:
      code: "123456"
    target:
      entity_id: alarm_control_panel.my_alarm_panel
```
2. **Disarm home when arrive**:
```yaml
mode: single
triggers:
  - trigger: state
    entity_id:
      - person.userOne
      - person.userTwo
    to: home
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: alarm_control_panel.my_alarm_panel
        state: disarmed
actions:
  - action: alarm_control_panel.alarm_disarm
    data:
      code: "123456"
    target:
      entity_id: alarm_control_panel.my_alarm_panel
```

Hope this help 😊
