### ISSUE TITLE
Call any service in notification task

### ISSUE THREAD

**Issue by kristjanbjarni** [nielsfaber/alarmo#1113]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Currently you can only use notify.* and similar services for notifications. It would be much more flexible to be able to call any action or service for notifcations.

As an example I have a shell command action that I can use to send SMS directly to a phone but currently I can't use that for any notifications in Alarmo.  It would look something like this in the Task editor in YAML mode:

```yaml
service: shell_command.send_sms
data:
  number: 1234567890
  message: "{{open_sensors}}"
```

**Comment by Ltek** [comment]
Bumper cars

**Comment by kristjanbjarni** [comment]
I am currently using a workaround by using the custom component pyscript and creating a pyscript notify wrapper that calls the service but this adds an unnecessary complexity just for a simple notification.

**Comment by soif** [comment]
@nielsfaber It would be really usefull. 🙏 

In my case I also have a script that send an SMS message, and another that post to our company internal message app.

It could be located either in the notifications or in the actions section, with a YAML configuration (or UI) to edit what data are sent to the script or service

_This would also close at least #1122 and #1136._

**Comment by kristjanbjarni** [comment]
Bump

**Comment by kristjanbjarni** [comment]
This feature would be really useful

**Comment by soif** [comment]
bumping... 🙏

**Comment by Soukyuu** [comment]
Oh nooo.

**Comment by Soukyuu** [comment]
Still would like to have this...

**Comment by nico97118** [comment]
Why not simply use a [command line notifier](https://www.home-assistant.io/integrations/command_line/#notify) 

I don’t think it would be a good idea to allow notification actions to call arbitrary services. The UI is designed around the notify service format and cannot infer which fields would be required for a custom service call.

Making it completely open-ended might provide more flexibility, but it would also make the feature less user-friendly for casual users.

That said, I understand that several people are trying to achieve this, so here is a simple workaround that provides similar behavior:

**Step 1 - Add a command line notifier**
In configuration.yaml, add a command line notifier : 
```yaml
command_line:
  - notify:
      name: my_shell_notify
      command: "/config/scripts/notify.sh"
```

 **Step 2 - Create the script**
Here is a notify.sh exemple, added in `scripts` directory under my home assistant config dir.
```bash
#!/bin/bash

MESSAGE=$(cat)

echo "$MESSAGE" >> /config/message.log
```

**Step 3 — Use your custom notifier**
Now you should have a custom notifier : `notify.my_shell_notify`
You can test it from Developer Tools → Services:
```yaml
action:
  - service: notify.my_shell_notify
    data:
      message: "MESSAGE"
```

**⚠️ Important limitation**

The command_line notifier only passes data through STDIN, which means only the message field is available in your script.

If you need to pass additional data, you’ll need to encode it inside the message field and parse it in your script. This is a current limitation of Home Assistant Core.

Example:
```yaml
action:
  - service: notify.my_shell_notify
    data:
      message: '{"phone":"123456789","message":"message"}'
```

**Using with Alarmo**

You can then use this notifier in Alarmo notifications.
Keep in mind that the title field is not passed to the script, so you’ll need to include everything inside the message.

⸻

I’ll leave it at that so everyone can adapt it to their own needs.

One last note: Home Assistant already provides many notification integrations: https://www.home-assistant.io/integrations/#notifications
It’s often worth checking if one already fits your use case before reinventing the wheel 😉

Hope this helps :)

**Comment by Soukyuu** [comment]
In my case, I'd like to forward the alert to my HA notification script. The HA notify integration is a bit inflexible in the sense that I either have to notify everyone, or each mobile app selectively. In my script I can set which people I want to notify and set unified parameters for each target. I'm not sure I can do that with the command line notifier

**Comment by nico97118** [comment]
Hi @Soukyuu 
I’m not sure I fully understand what led you to choose a Home Assistant script instead of calling the notify service directly.
However, I assume you have good reasons for doing so.

For advanced use cases like yours, handling Alarmo events outside of the built-in notifications/actions is the right approach.

## Example
As an example, I’ll use the case mentioned in this issue. Let’s say you want to call a script when the alarm is triggered and pass `{{ open_sensor }}` to it as data.

### My alarmo entity
I have an alarmo entity `alarm_control_panel.inside`

### Automation

I create an automation triggered when the alarm is triggered.
This automation calls a script and sends the value of open_sensors *(parsed from the entity’s attributes)*.

Here is an example: 
```yaml
alias: triggered_to_script
description: ""
triggers:
  - trigger: state
    entity_id:
      - alarm_control_panel.inside
    to:
      - triggered
conditions: []
actions:
  - action: script.script_notifyer_example
    metadata: {}
    data:
      message: >-
        {% for item in state_attr("alarm_control_panel.inside","open_sensors") %} 
        {{ item }}
        {% endfor %}
mode: single
```

### Script
As you might notice, I call a script from the automation and pass the relevant data as an argument.
Here is an example script that expects a text input (message). 
In this example, it simply calls a notify service with the input content (message) as the message.

```yaml
sequence:
  - action: notify.mobile_app_iphone
    metadata: {}
    data:
      message: "{{ message }}"
fields:
  message:
    selector:
      text: null
    name: message
    required: true
alias: script_notifyer_example
```

### Explanations

To summarize the flow:
- The alarm entity state is monitored via a Home Assistant automation.
- The automation uses the entity’s attributes (e.g. `changed_by`, `open_sensors`, `bypassed_sensors`, …) depending on your needs.
- Here, I start a script and pass the value I want to work with to it (as `message` argument).

*Notes:*
I could also call the notifier directly from the automation.
I could also use the automation to simply trigger the script without passing any data, and rely on a dedicated script designed specifically to send notifications using the alarm entity’s attributes.

---

There are many possibilities depending on your preferences.
The main idea here is to show how to take advantage of Alarmo’s exposed attributes to gain more flexibility in your actions, while still using the available “wildcards” (e.g. changed_by, open_sensors, bypassed_sensors, …).

I Hope this will help you to achieve what you're trying to do.

----

However, I maintain my position regarding the feature request. I still believe Alarmo’s built-in actions/notifications are intended for casual users who want to easily set up basic actions, and in my opinion, it should remain that way.


To go further
----
Be advised that the open_sensors attribute from the alarm entity will return the open sensors ID's (see the following screenshot)

<img width="1129" height="306" alt="Image" src="https://github.com/user-attachments/assets/c6f298a9-f9dd-411b-8af4-56ad1ac7ace3" />

If I want to resolve the friendly name, I'll need to call state_attr on item to request its friendly_name:
```jinja2
{% for item in 
  state_attr("alarm_control_panel.inside","open_sensors") 
%}
  {{ state_attr(item,"friendly_name") }}
{% endfor %}
```
