### ISSUE TITLE
Temperature sensors as alarms

### ISSUE THREAD

**Issue by RoboKaren** [nielsfaber/alarmo#1114]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
[It'd be great if Alarmo had [tempreature] added as an environmental sensor as well. I appreciate the leak detection!  I would also like alarms if certain thermostat entities drop below zero (freeze warning) as well as if certain thermostats go above zero (freezer) or above 10C (refrigerator). For some of us, this could save a lot of money!]

### Additional info
[Temperature sensors would need a threshold below or threshold above value to trip.]

**Comment by RoboKaren** [comment]
Now yes, I can do this as an automation in HA but it takes making an extra script for each one -- and then I have to script in the notification / alarm etc. Alarmo has this functionality already.

**Comment by kabakakao** [comment]
Also a Heat Alarm (>50 degree) would be cool for rooms where smoke Alarm makes no sense (Kitchen)

**Comment by Trexano99** [comment]
You can easily create a binary sensor with template and use it in alarmo as a safety device.
Setup:

```yaml
template:
  - binary_sensor:
      - name: "Thermostat temperature below alert value"
        state: "{{ states('sensor.your_sensor_here)|float(0) < 0 }}"
        device_class: safety
      - name: "Thermostat temperature above alert value"
        state: "{{ states('sensor.your_sensor_here)|float(0) > 10 }}"
        device_class: safety
```
