### ISSUE TITLE
Actionable notification not working in home assistant 2025.3.0

### ISSUE THREAD

**Issue by zd3sf** [nielsfaber/alarmo#1126]
### Checklist

- [x] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [x] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.7

### HA Version

2025.3.0

### Bug description

Actionable notification `ALARMO_DISARM` was working in previous versions. Not sure what home assistant version broke it. It shouldn't break because the code is independent of home assistant

Notification YAML:
```
service: notify.mobile_app_poco_f3
data:
  message: Alarm triggered! {{open_sensors|format=short}}.
  title: Alarmo
  data:
    ttl: 0
    command: normal
    importance: max
    priority: high
    channel: alarm_stream
    notification_icon: mdi:shield-home
    color: red
    car_ui: true
    actions:
      - action: ALARMO_DISARM
        title: Disarm
```

Relevant code:
```
            if action == const.EVENT_ACTION_FORCE_ARM:
                _LOGGER.info("Received request for force arming")
                alarm_entity.async_handle_arm_request(arm_mode, skip_code=True, bypass_open_sensors=True)
            elif action == const.EVENT_ACTION_RETRY_ARM:
                _LOGGER.info("Received request for retry arming")
                alarm_entity.async_handle_arm_request(arm_mode, skip_code=True)
            elif action == const.EVENT_ACTION_DISARM:
                _LOGGER.info("Received request for disarming")
                alarm_entity.alarm_disarm(None, skip_code=True)
            else:
                _LOGGER.info("Received request for arming with mode {}".format(arm_mode))
                alarm_entity.async_handle_arm_request(arm_mode, skip_code=True)
```

### Steps to reproduce

Trigger Alarm
Notification received
Disarm button pressed
Alarm did not disarm

### Relevant log output

```shell

```
