### ISSUE TITLE
Can't get the State of ready_to_arm by using template as described in doc's

### ISSUE THREAD

**Issue by olderbag** [nielsfaber/alarmo#1173]
### Checklist

- [x] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [x] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.8

### HA Version

2025.5.3

### Bug description

The code, provided in the doc's for Creating readiness indicator entities:
```
template:
  - triggers:
      - trigger: event
        event_type: alarmo_ready_to_arm_modes_updated
        event_data: 
          entity_id: alarm_control_panel.alarmo
    binary_sensor:
      - name: "Alarmo Ready To Arm Away"
        state: '{{ trigger.event.data.armed_away }}'

```
creates the entity, but it doesn't change its state, remains "unknown".

### Steps to reproduce

I set up a new, virgin HA. Installed
- Studio Code Server
- HACS
- Alarmo
- Alarmo Card

Alarmo is left unchanged after installation. 
Only one area, the default "Alarmo"
Only one sensor added, generated by a Template for a binary sensor.

Created a test Dashboad and added the Alarmo card.

In the card i can see the readyness state. It changes the color red/green according to the state of the above mentioned binary sensor.

Added the code, provided in the doc's for Creating readiness indicator entities in configuration.yaml exactly as proposed.

The entity "binary_sensor.alarmo_ready_to_arm_away" was created with state "unknown". But this entity doesn't change its state according to readiness of "Arm Away". The indicator in the card does (red/green), but the entity not.

Testing the event in developer tools:
Listen to event: alarmo_ready_to_arm_modes_updated
No output when ready to arm changes green/red.

**Log Output:**
`2025-06-03 16:01:21.339 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.test_offnung changed: old_state=closed, new_state=open
2025-06-03 16:01:21.339 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] ready_to_arm_modes for Alarmo updated to 
2025-06-03 16:02:15.058 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.test_offnung changed: old_state=open, new_state=closed
2025-06-03 16:02:15.058 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] ready_to_arm_modes for Alarmo updated to away, home
2025-06-03 16:02:22.126 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.test_offnung changed: old_state=closed, new_state=open
2025-06-03 16:02:22.126 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] ready_to_arm_modes for Alarmo updated to `
