### ISSUE TITLE
Feature Request: Add option to enable critical notifications

### ISSUE THREAD

**Issue by shred86** [nielsfaber/alarmo#168]
When creating a new notifications from the Actions tab, add an option/toggle switch to enable [critical notifications](https://companion.home-assistant.io/docs/notifications/critical-notifications). This is particularly nice to have for notifications when the alarm is pending or triggered. I realize this is already possible by switching to the yaml view and adding the specified parameters, but it's just a small tweak that I'm sure users would appreciate.

**Comment by nielsfaber** [comment]
I don't think this can be added to Alarmo, since it is not possible for me which type of device is targeted (iOS, Android, or other) for the notification. 
Therefor it should remain a manual action, I think the yaml view is the best option.

**Comment by shred86** [comment]
Ah, I was thinking both could just be added and depending on whichever device you have, it would work for either or. Something like:
```
        data:
          ttl: 0
          priority: high
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
```
Adding it manually is easy enough for me - just looking for ways to improve this awesome integration! Thanks again for the work.

**Comment by nielsfaber** [comment]
>  I was thinking both could just be added and depending on whichever device you have, it would work for either 

I don't know enough about HA to be able to judge whether doing so has any negative side effect.
Usually an integration validates the data that is provided with a service call. If extra/unexpected properties are provided, it might result in an error and the task may be ignored.

Perhaps I could add some option in the editor to assign Android/iOS as notification target, but I would have to look at the bigger picture (ideally I would allow the [actionable ](https://github.com/nielsfaber/alarmo#actionable-notifications) to be set up by the editor as well).

Let's keep this request open for now 👍

**Comment by shred86** [comment]
I only have iOS devices unfortunately but I did add the `ttl: 0` and `priority: high` to my `data:` block and it doesn't throw any errors on the HA side, and critical notifications work. I wish I had an android device to test with. I'm assuming it would work because using a target of `notify` (which is what I use), there could be users with both iOS and Android devices so I'd imagine both critical notification parameters would have to be accepted.

**Comment by j73123** [comment]
I'm looking for this as well. Critical notifications is a must have and would be the reason for not choosing Alarmo - I don't mind adding this manually in YAML - as long as I can configure it - just can't get it to work though ...

This is working fine for iPhone in a normal automation action

```
service: notify.notify
data:
  message: ALARM! The alarm has been triggere
  data:
    sound:
      name: default
      critical: 1
      volume: 1
```

Trying to this in Alarmo - based on your input @shred86 

```
service: notify.mobile_app_my_iphone
entity_id: null
service_data:
  title: HA Alarm
  message: 'ALARM! The alarm has been triggered: cause: {{open_sensors}}'
  ttl: 0
  priority: high
  push:
    sound:
      name: default
      critical: 1
      volume: 1
```
Using "Try IT' doesn't work ttkd and priority is not allowed - obviously as this is not a part of the Alarmo syntax - nevertheless I can't get the notification to work via a normal alarm.

Any suggestion on what to change on the YAML code ?

@nielsfaber you could add a checkbox 'iPhone' or similar - a lot of notification a specifically for iPhone and some eventually for Android - and then allow some UI for iPhone user and others for Andoid.

**Comment by j73123** [comment]
This working - data line added - but unable to save script - due to **entity: null** ....

```
service: notify.mobile_app_iphone
service_data:
  title: HA Alarm
  message: 'ALARM! The alarm has been triggered: cause: {{open_sensors}}'
  data:
    push:
      sound:
        name: default
        critical: 1
        volume: 1

```

**Comment by nielsfaber** [comment]
@j73123 as far as I know Alarmo supports all settings that HA supports, and you should be able to save it as such.
I set up a notification like this:
```
service: notify.mobile_app_iphone
service_data:
  title: ''
  message: The alarm is set to {{arm_mode}}
  data:
    sound:
      name: default
      critical: 1
      volume: 1
```
It works both using "Try it" and after saving + arming the alarm.
On my iPhone it shows up as critical and with a different sound:
![image](https://user-images.githubusercontent.com/16861605/121796646-f8c7ed00-cc1a-11eb-9c23-0657dc634372.png)

I don't really know what I do different than you.
Perhaps you are running an older version of Alarmo? 
(there were some bugs in the previous version due to the many changes I made)
