### ISSUE TITLE
Alarm not triggered by always armed sensor

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#170]
Just testing one of the last things I haven't yet tested on the alarm system, the integration of smoke detectors. one accidentally went off today:
![image](https://user-images.githubusercontent.com/1751192/113211596-2e269500-92d2-11eb-8beb-14e86d63f78f.png)

But the alarm didn't. am I missing some sort of configuration issue? Configuration here:
![image](https://user-images.githubusercontent.com/1751192/113211680-4ac2cd00-92d2-11eb-9ebb-0374edd66a76.png)

Anything else I should look at?

Thanks!

**Comment by nielsfaber** [comment]
Hi Stefan,
I did some testing for this scenario, in my case all went as expected.
So unfortunately I haven't been able to reproduce the issue you are experiencing.
This issue sounds concerning for me, because such problems affect the reliability of Alarmo (having the sensor responses work reliably is the highest priority for Alarmo).

I would like to ask you to enable the debug logging for alarmo and reproduce the scenario.
You can do so by adding the following in the configuration.yaml of HA:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```

The expected logging would be similar to this (I changed my backdoor into an environmental sensor for testing):

> 2021-04-05 07:09:16 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.backdoor changed: old_state=closed, new_state=open
2021-04-05 07:09:16 DEBUG (MainThread) [custom_components.alarmo.sensors] Alarm is triggered due to an always-on sensor: binary_sensor.backdoor
2021-04-05 07:09:16 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.alarmo was updated from disarmed to triggered
2021-04-05 07:09:16 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.alarmo is updated from disarmed to triggered

For the sake of testing you could add a dummy sensor to HA as well:
```
input_boolean:
  dummy_sensor: {}

binary_sensor:
  - platform: template
    sensors:
      dummy:
        value_template: "{{ is_state('input_boolean.dummy_sensor', 'on') }}"
        device_class: smoke
        friendly_name: Dummy Sensor
```
This would create a sensor you can manually set using the input_boolean.

Please keep me posted if you have any findings.
Thanks in advance.
