### ISSUE TITLE
When setting alarm to home and skip delay true with automation, the event is still sent

### ISSUE THREAD

**Issue by thanksmister** [nielsfaber/alarmo#218]
I am using MQTT to set an external alarm application (MQTT Alarm Panel).  I am running an automation to set the alarm to home without  a delay at a certain time each night.   What I am seeing is that the alarm still receives the event ARM_HOME with delay "0"  at the same time it receives the mode "armed_home".    Having both with multiple MQTT applications connected to the same broker causes  a race condition on some devices. 

Automation:

```
alias: Enable Alarm Night
trigger:
  - at: '21:00'
    platform: time
condition: []
action:
  - service: alarmo.arm
    data:
      code: '1234'
      entity_id: alarm_control_panel.alarmo
      mode: home
      skip_delay: true
      force: true
mode: single
```

Topic Received:

`armed_home`

MQTT Event Received:

`{"event":"ARM_HOME","delay":0}`

Expected behavior:

I would not expect to receive an event when the delay is 0 since the topic with alarm state `armed_home` is arriving at the same time.    I would only expect to receive the topic state `armed_home' with this automation.  Note the `skip_delay' flag is true, but also in Alarmo configuration, exit delay for Home mode is also 0.

<img width="702" alt="Screen Shot 2021-05-31 at 9 42 30 AM" src="https://user-images.githubusercontent.com/142340/120194939-991e1a80-c1f4-11eb-9850-6d1fe5f713f7.png">
