### ISSUE TITLE
Add media-player to play siren sound

### ISSUE THREAD

**Issue by andrebbruno** [nielsfaber/alarmo#241]
Would it be possible over actions to add a multimedia option to play a file like a siren?

I only see options to switch on and off, so not sure if I should create this switch outside of the actual integration, or if this is something that can be added to the integration itself.

thanks and keep up the great work!

**Comment by nielsfaber** [comment]
I think this is possible by executing service `media_player.play_media`.
It depends on your media player of course.

For example (using Google Nest Hub):
```
- service: media_player.play_media
  entity_id: media_player.living_room_display
  service_data:
    media_content_id: 'some-sound.mp3'
    media_content_type: music
```

You can define such action by switching to the yaml mode in the action editor.
It should allow for more advanced tasks rather than just switching on/off a device.
