### ISSUE TITLE
"Unsupported" entity IDs removed when re-entering Action settings

### ISSUE THREAD

**Issue by docbobo** [nielsfaber/alarmo#267]
I'd like to use Alarmo in combination with my Arlo cameras. To achieve this, I basically need to arm another Alarm Control Panel when the Alarmo Control Panel gets armed (and the opposite when disarming). Theoretically, I should be able to do that via the Actions, but the entity list does not display the other control panels. 

YAML mode to the rescue:

```
- entity_id: alarm_control_panel.aarlo_control_panel
  service: aarlo.alarm_set_mode
  service_data:
    mode: armed
```

This snippet works without a problem. However: when I edit the action and switch to YAML, it becomes this:

```
- service: aarlo.alarm_set_mode
  service_data:
    mode: armed
```

So it's basically removing the entity because they are not support in the UI.

Now I can easily see why you would say "That's not a bug", but still... 

(Great job with the component, btw)
