### ISSUE TITLE
Siren not turning off 

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#360]
### Alarmo Version

1.8.1

### HA Version

2021.12

### Bug description

Siren doesn't turn off when the alarm is no longer triggered (via disarm in this case)

### Steps to reproduce

This action:
![image](https://user-images.githubusercontent.com/1751192/147044059-7b42638f-a15a-4bda-8564-4fe6e1f37e2c.png)

Arm the alarm, trigger it.  Siren comes on.  Disarm alarm, siren stays on.  Now I could add an automation for when it disarms, but the options under events doesn't include when the alarm is no longer triggered (after 5 minutes in my case).

Am I missing something?

**Comment by Eyco1981** [comment]
Your siren seems to be a simple switch in HA (same as my Z-Wave siren). As Alarmo has no option "turn on until condidion", you need to create these conditions yourself (e.g. turn siren of on disarmed and armed). In my opinion the easiest way is to create a script in HA which will be triggered by Alarmo and stops the siren, as soon as there is no triggered state anymore. 

My script:
```
alias: 'Alarmo: Siren'
sequence:
  - condition: state
    entity_id: alarm_control_panel.master
    state: triggered
  - service: switch.turn_on
    target:
      entity_id: switch.siren
  - wait_for_trigger:
      - platform: state
        entity_id: alarm_control_panel.master
        from: triggered
    continue_on_timeout: false
  - service: switch.turn_off
    target:
      entity_id: switch.siren
mode: single
icon: mdi:bullhorn
```
