### ISSUE TITLE
Feature to arm / disarm alarmo with other entity 

### ISSUE THREAD

**Issue by johanvh83** [nielsfaber/alarmo#378]
### Checklist
- [ ] I checked for similar existing requests (both open and closed) before posting. -> DONE 
- [ ] My request is generic, other users may benefit from it too. -> SURE

### Proposal
I'm sure others are also searching for keypad solutions. 

### Additional info
The keypad with RFID has a relay that activates for 3 seconds, once the code in entered correctly or the tag is valid.
I will connect the relais output of the keypad/RFID reader to a GPIO of an ESP module. 
This way in HA I have an entity that will change it state when the relais of the keypad is activated.
I've seen your recommandation to use an automation to arm/disarm automatically https://github.com/nielsfaber/alarmo#automatic-arming but it's based on a static state; I clarify:
switch off = armed
switch on = disarmed
In my case I have the relay that closes for 3 seconds.
Based on this change the Alarmo state should change to armed (if it was disarmed) or vice versa. A kind of toggle feature.
Maybe the automation can be changed but I have no idea how to do that.
Thanks for your help!

**Comment by nielsfaber** [comment]
This is not a valid feature request.
You are asking for help on creating a custom automation for your DIY keypad, this is not the place for that.

Anyways, below is a starting point (i didn't test it).
Next time, please use the HA forum for support questions.

Automation for arming:
```
trigger:
  - platform: state
    entity_id: switch.my_remote
    to: 'on'
condition: # only execute this rule if the alarm is disarmed
  - condition: state
    entity: alarm_control_panel.alarmo
    state: disarmed
action:
  - service: alarmo.arm
    data:
      entity_id: alarm_control_panel.alarmo
      code: '1234'
      mode: away 
```

Automation for disarming:
```
trigger:
  - platform: state
    entity_id: switch.my_remote
    to: 'on'
condition: # only execute this rule if the alarm is not disarmed
  condition: not
  conditions:
    - condition: state
      entity: alarm_control_panel.alarmo
      state: disarmed
action:
  - service: alarmo.disarm
    data:
      entity_id: alarm_control_panel.alarmo
      code: '1234'
```
