### ISSUE TITLE
Manual automation not working

### ISSUE THREAD

**Issue by tremebundo** [nielsfaber/alarmo#42]
I am trying to make an automation to disarm the alarm when a NFC tag is read.
In automations I have a call to this service:
```
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarmo
```

But the service is not executed.
Also, if I check with the service developer tools, no disarm is made.

![Captura de pantalla 2020-11-27 a las 18 38 25](https://user-images.githubusercontent.com/35578150/100474353-b0af0600-30e0-11eb-933d-98fb859c8228.png)
May be I am doing something wrong?

**Comment by nielsfaber** [comment]
This will only work if the alarm does not require a code.
This you check the log?

**Comment by tremebundo** [comment]
I have just confirmed.
Thanks for your quick response.
But, what about this service call:

```
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarmo
      code: 1234
```
That is the example exposed for that service call.
That way, both methods (manual automation and integrated user policies at your component) should be valid.
I would like some users to enter a code and me to read my NFC.

**Comment by nielsfaber** [comment]
That should work. Maybe you should enter the code as a string, so "1234". 

> That way, both methods (manual automation and integrated user policies at your component) should be valid.

I'm not sure what you mean here.
If you require a code for the disarm action, it should be always provided with the service call.

> I would like some users to enter a code and me to read an NFC. I read my NFC card with my phone with HA installed on it.
But I do not want my employees to have my HA instance installed.

I don't know how NFC works on the phone. 
If you can create an automation that disarms when valid NFC is provided, it should work.
But still, the automation should contain a code.

Alarmo cannot detect which method was used (Lovelace alarm panel card or automation) for disarming.

**Comment by tremebundo** [comment]
Checked, and working.
I can confirm this automation is working:

```
  trigger:
  - platform: tag
    tag_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarmo
      code: "xxxx"
```

Thanks a lot for your support.
