### ISSUE TITLE
Support several codes for the same user

### ISSUE THREAD

**Issue by DamGranger** [nielsfaber/alarmo#488]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
In the codes panel I have to duplicate my users with a pin code and an RFID tag. I currently use "_name_ PIN" and "_name_ badge". But it could be better if I could register several codes for the same user.

### Additional info
My alarm system is managed through a Frient KEYZB-110 keypad. This keypad has the ability to send commands with a typed pin code or with an RFID tag.

Payload with a pin code :
` '{"action":"disarm","action_code":"0000","action_transaction":3,"action_zone":23,"battery":100,"battery_low":false,"last_seen":"2022-06-02T23:28:48+02:00","linkquality":255,"tamper":false,"update":{"state":"idle"},"update_available":false,"voltage":6300}'`

Payload with an RFID tag scanned :
`'{"action":"disarm","action_code":"+A21C1DF4","action_transaction":3,"action_zone":23,"battery":100,"battery_low":false,"last_seen":"2022-06-02T23:28:48+02:00","linkquality":255,"tamper":false,"update":{"state":"idle"},"update_available":false,"voltage":6300}'`

These are handled by an HA automation that triggers alarmo.arm or alarmo.disarm service depending on the "action" value and passes the code with :
`'{{trigger.to_state.attributes.action_code}}'`

I think that it could be handy to be able to register both codes under the same user in Alarmo so we wouldn't have to duplicate persons with wierd names. I don't need to track if my wife disarmed the alarm using her pin code or her badge, I just need to know it's my wife.

**Comment by nielsfaber** [comment]
I'm afraid that 'by design' a user can only have a single code, so it will be required to create extra users for this.

However, the user names don't have to be unique, so you can make multiple user-code combinations by re-using the names.
The remaining problem is that you will have to distinguish between the codes yourself.

If it helps you I could add some text field with user description. I don't know what I could do more to help your case.

**Comment by DamGranger** [comment]
@nielsfaber Thanks for your answer. As I explained, in the short description, there is a simple workaround that I currently use. I just thought it could be more elegant to have this kind of option. If, by design, it's not feasible, then you can drop this FR. There is not really a need for a description field for two reasons :
- I can name users differently, I have no use for the distinction but it doesn't create any issue per se.
- Even if you name users the same way, one would be a PIN and the other one would be a password, so it's already easy to distinguish them in the UI.

**Comment by JWynegar** [comment]
> ### Checklist
> * [x]  I checked for similar existing requests (both open and closed) before posting.
> * [x]  My request is generic, other users may benefit from it too.
> 
> ### Proposal
> In the codes panel I have to duplicate my users with a pin code and an RFID tag. I currently use "_name_ PIN" and "_name_ badge". But it could be better if I could register several codes for the same user.
> 
> ### Additional info
> My alarm system is managed through a Frient KEYZB-110 keypad. This keypad has the ability to send commands with a typed pin code or with an RFID tag.
> 
> Payload with a pin code : ` '{"action":"disarm","action_code":"0000","action_transaction":3,"action_zone":23,"battery":100,"battery_low":false,"last_seen":"2022-06-02T23:28:48+02:00","linkquality":255,"tamper":false,"update":{"state":"idle"},"update_available":false,"voltage":6300}'`
> 
> Payload with an RFID tag scanned : `'{"action":"disarm","action_code":"+A21C1DF4","action_transaction":3,"action_zone":23,"battery":100,"battery_low":false,"last_seen":"2022-06-02T23:28:48+02:00","linkquality":255,"tamper":false,"update":{"state":"idle"},"update_available":false,"voltage":6300}'`
> 
> These are handled by an HA automation that triggers alarmo.arm or alarmo.disarm service depending on the "action" value and passes the code with : `'{{trigger.to_state.attributes.action_code}}'`
> 
> I think that it could be handy to be able to register both codes under the same user in Alarmo so we wouldn't have to duplicate persons with wierd names. I don't need to track if my wife disarmed the alarm using her pin code or her badge, I just need to know it's my wife.

I know this is not related to that but somehow could you share your HA automation for the keypad

**Comment by DamGranger** [comment]
It's really straight forward. Please note I only use arm_away and disarm, but the keypad has 5 buttons so you could make them all, just use the same pattern, if you do and want to keep it simple you could simply remove the condition on the alarm being disarmed when arming :

```
alias: SE alarm keypad
description: ''
trigger:
  - platform: state
    entity_id:
      - sensor.kp_ent_action
    to: arm_all_zones
    id: arm
  - platform: state
    entity_id:
      - sensor.kp_ent_action
    to: disarm
    id: disarm
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: arm
          - condition: device
            device_id: fefa15bb7f11dad9cbc2917f54fee60c
            domain: alarm_control_panel
            entity_id: alarm_control_panel.general
            type: is_disarmed
        sequence:
          - service: alarmo.arm
            data:
              entity_id: alarm_control_panel.general
              mode: away
              code: '{{trigger.to_state.attributes.action_code}}'
      - conditions:
          - condition: trigger
            id: disarm
        sequence:
          - service: alarmo.disarm
            data:
              entity_id: alarm_control_panel.general
              code: '{{trigger.to_state.attributes.action_code}}'
    default: []
mode: single
```
