### ISSUE TITLE
Adding Images to Notification 

### ISSUE THREAD

**Issue by MrPresident2** [nielsfaber/alarmo#498]
### Alarmo Version

v1.4.1

### HA Version

2021.6.2

### Bug description

Hey Guys,
While trying to make a push notification (in this case for an android device) I can’t add an image like I can add it under regular automation - push notification ( notify. )
This might be a user error but I still would like to get some help, Thanks.
Is that something that I'm doing wrong or a bug that we cant send images through Alarmo notifications? 
What I’m trying to write that is working in regular automation:
````
service: notify.addnamehere
data:
  title: ALARM
  message: The Alarm Is Disarmed
  data:
    image: /local/Notification_PNGs/nameofimage.png



### Steps to reproduce

_No response_

### Relevant log output

_No response_

**Comment by zollek** [comment]
Hi, I'm using:
**Alarmo Version** v1.9.4
**HA Version** 2021.6.4
and don't see any problem sending image notifications by telegram.

YMAL code i'm using in the Alarmo actions:
```
service: notify.telegram_******
service_data:
  title: ''
  message: Grafika
  data:
    photo:
      - file: /config/www/graphics/Alarmo/Alarm_armed_custom.png
        caption: ''
```
Maybe try to send your notification through Services in Developer Tools and see if You can get it.
I can't help You with android push notification becasue I've never used it.
