### ISSUE TITLE
ios actionable notification - action not working

### ISSUE THREAD

**Issue by TomKaltz** [nielsfaber/alarmo#53]
The notification is received but when I push the "Retry Arm" button on ios an error occurs in HA core.  I've set up the actionable notification as follows and the error is below.

```yaml
ios:
  push:
    categories:
      - name: Alarm Arm Failure
        identifier: alarmo_arm_failure
        actions:
          - identifier: ALARMO_RETRY_ARM
            title: Retry Arm # feel free to change this text
            destructive: true
          - identifier: ALARMO_FORCE_ARM
            title: Force Arm # feel free to change this text
            destructive: true
```

`2020-12-08 11:43:53 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 598, in async_handle_event
    elif event.data["action"]:
KeyError: 'action'`

**Comment by nielsfaber** [comment]
Hmm weird.
In my code I made a distinction between iOS and Android format:
```
            if (
                event.data and "categoryName" in event.data
                and "actionName" in event.data
                and event.data["categoryName"] in EVENT_CATEGORIES
            ):
                # IOS push notification format
                action = event.data["actionName"]
            elif event.data["action"]:               <----- line 598
                # Android push notification format
                action = event.data["action"]
```
Since the first statement is missed (i take you for someone with programming skills 🙂 ), it seems that the feedback from the push message did not have the correct format / misses some parameters.

Could you share the yaml code of your notification setup (the one that handles the failed-to-arm)?

**Comment by TomKaltz** [comment]
```yaml
name: Push Notify Failed To Arm
modes:
  - armed_home
triggers:
  - event: arm_failure
actions:
  - service: notify.mobile_app_tk_iphone
    service_data:
      message: 'The alarm could not be armed due to: {{open_sensors}}.'
      title: Failed To Arm Alarm
      data:
        push:
          category: alarmo_arm_failure
```
