### ISSUE TITLE
Can't set phone number when using twilio integration as notification

### ISSUE THREAD

**Issue by krustophenia** [nielsfaber/alarmo#555]
### Alarmo Version

v1.9.4

### HA Version

2022.8.4

### Bug description

When trying to use twilio integration as a new notification and setting a phone number using yaml, it returns an error.
I'm not sure if that's a bug or should be moved to a feature request in order to add extra keys.

### Steps to reproduce

When I try to configure an action when the alarm is triggered, I try to configure it using yaml like this:

```
service: notify.twilio_calls
service_data:
  message: "test"
  title: "test"
  target: +XXXXXXXXXXX
```
When I click on try it, it successfully calls me on my phone but when I try to save it says:
```
Something went wrong!
Message format incorrect: extra keys not allowed @ data['actions'][0]['service_data']

Response error: 400

Please [report](https://github.com/nielsfaber/alarmo/issues) the bug.
```
