### ISSUE TITLE
Service_data in YAML mode not accepted.

### ISSUE THREAD

**Issue by Telain** [nielsfaber/alarmo#592]
### Alarmo Version

v1.9.6

### HA Version

2022.10.4

### Bug description

Changing notification data to service_data isn't working.

Referencing this issue for setup: #472 

Trying to apply this:
```
service: notify.mobile_app_telainphone
service_data:
  message: "The alarm is triggered! Cause: {{open_sensors}}."
  title: ""
  data:
    channel: SecurityPrio
    importance: max
    persistent: true
    tag: persistent
    color: red
```

Just testing with the below and the example in #472 (with the notify target changed) don't work either.
```
service: notify.mobile_app_telainphone
service_data:
  message: "The alarm is triggered! Cause: {{open_sensors}}."
  title: ""

```

### Steps to reproduce

Enter notification, switch to YAML mode, change data to service_data, edit message, test. Notification received is still the message from before changing.

**Comment by nielsfaber** [comment]
You don't need to use `service_data` anymore. This is now replaced by `data` to be consistent with HA.

**Comment by Telain** [comment]
How is it supposed to be entered?
This
```
service: notify.mobile_app_telainphone
data:
  message: "The alarm is triggered! Cause: {{open_sensors}}."
  title: ""
  channel: SecurityPrio

```
Gives me an error: `extra keys not allowed @ data['channel']`

**Comment by nielsfaber** [comment]
```
service: notify.mobile_app_telainphone
data:
  message: "The alarm is triggered! Cause: {{open_sensors}}."
  title: ""
  data:
    channel: SecurityPrio
    importance: max
    persistent: true
    tag: persistent
    color: red
```

**Comment by Telain** [comment]
Nevermind, I referenced one of my notification automations. It's

```
service: notify.mobile_app_telainphone
data:
  message: "The alarm is triggered! Cause: {{open_sensors}}."
  title: ""
  data:
    channel: "SecurityPrio"

```
