### ISSUE TITLE
Actionable Notifications - Force Arm not working

### ISSUE THREAD

**Issue by onkytonk** [nielsfaber/alarmo#60]
I have implemented actionable notifications on ios. 

The options come up perfectly fine when I there is an open sensor, however, when I try to "Force Arm" the exit delay begins again, but then it still fails to arm. This is an endless loop, and I'm never able to force arm the system. 

Not sure what I'm missing, or if its a bug. 

I have added the yaml into the config, and I have added the extra yaml to the notification under "service_data".

**Comment by nielsfaber** [comment]
Could you share the config of your action (YAML) and in the configuration.yaml (if you use iOS)?
Also, can you share the HA log entries of this scenario?

**Comment by onkytonk** [comment]
I have other actionable notifications working, so quite certain the other configs are correct. 

I can't seem to see anything related in my log. Perhaps I haven't got the correct log turned on in my config.

This is in my ios.yaml:

```
push:
  categories:
    - name: Alarm Arm Failure
      identifier: alarmo_arm_failure
      actions:
        - identifier: ALARMO_RETRY_ARM
          title: Retry Arm # feel free to change this text
          destructive: true
        - identifier: ALARMO_FORCE_ARM
          title: Force Arm # feel free to change this text
          destructive: true
```
