### ISSUE TITLE
Add Event "Wrong code"

### ISSUE THREAD

**Issue by seanmccabe** [nielsfaber/alarmo#645]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Add the event "Wrong Code" to Alarmo.
This is already in the log, so the event must fire somewhere.

This would be beneficial to know if someone is attempting to disarm the alarm whilst its pending or triggered and making failed attempts.

Had a few instances where the wrong code has been used (ie in an automation) resulting in alarm not disarming and then being triggered. Obviously goes un-noticed as no alert can currently be sent on this failure.

### Additional info
Much the same as the other events, allowing a notification can prove very beneficial.

**Comment by nielsfaber** [comment]
There is an ‘alarmo failed to arm’ event already

**Comment by nielsfaber** [comment]
Yes it does

**Comment by seanmccabe** [comment]
> Yes it does

Appears to not be working then. As using the incorrect code I do not get a failed to arm alert, nor an event in the log.

**Comment by nielsfaber** [comment]
This is the event fired when trying to disarm with wrong code. So by looking at the command and reason, you can filter out the scenario you're looking for.
```
event_type: alarmo_failed_to_arm
data:
  context_id: null
  command: disarm
  area_id: "1623385299"
  reason: invalid_code
origin: LOCAL
time_fired: "2023-01-11T19:43:36.128440+00:00"
context:
  id: 01GPH5QZP0GN7C4HRKQVSF35C8
  parent_id: null
  user_id: null

```

**Comment by Smiley1244** [comment]
Hi, I was also interested in triggering an event after an incorrect code has been entered. I can confirm the same findings as @seanmccabe . I get a failed to arm event triggered if a sensor is open and the system cannot arm but not for an incorrect code passed via alarmo lovelace card or event from Ring Keypad. I do get the trigger from both for an open sensor.
Would be nice to give some indication that an incorrect code has been entered. I do get the wrong code warnign i nthe logs 

```
Logger: custom_components.alarmo.alarm_control_panel
Source: custom_components/alarmo/alarm_control_panel.py:361
Integration: Alarmo ([documentation](https://github.com/nielsfaber/alarmo), [issues](https://github.com/nielsfaber/alarmo/issues))
First occurred: 18:02:42 (3 occurrences)
Last logged: 18:03:23

Wrong code provided.
```

It would be nice to have a seperate event for this if it's possible or to intercept it within HA?
Thanks

**Comment by Smiley1244** [comment]
To anyone that comes across this looking for the same answers :)
The issue I was having was I was tryign to use the "Failed to Arm" action in Alrmo which triggers during an arming event but not a disarming event. If you create your own automation usign the following trigger it works fine :) mine goes on to send a tone to the Ring Keypad V2
```
alias: "Alarm: Wrong Code Entered"
description: ""
trigger:
  - platform: event
    event_type: alarmo_failed_to_arm
    event_data:
      reason: invalid_code
condition: []
action:
  - service: zwave_js.set_value
    entity_id: sensor.keypad_v2_battery_level
    data:
      command_class: "135"
      property: "9"
      endpoint: "0"
      property_key: "1"
      wait_for_result: true
      value: 0
mode: single
```
