### ISSUE TITLE
Variables in notification action

### ISSUE THREAD

**Issue by popeating** [nielsfaber/alarmo#671]
When some sensro are triggered, i take a snapshot from a camera and store it with a filename composed by a fixed part and a timestamp; the timestamp of the latest snapshot is also saved in a variable.
i try to attach the snapshot on the notification that Alarmo allow to setup, but it looks like it is not able to send images with variable in their name.
if i use somthing like
```
service: notify.mobile_app_iphone
data:
  message: "L'allarme è stato attivato! Causa: {{open_sensors|lang=it}}."
  title: "Allarme attivato! "
  data:
    image: /media/camera/immagine_{{ states('input_text.snapdatetime') }}.jpg
```
it doesnt send the image
but if use
```
service: notify.mobile_app_iphone
data:
  message: "L'allarme è stato attivato! Causa: {{open_sensors|lang=it}}."
  title: "Allarme attivato! "
  data:
    image: /media/camera/immagine_23123423432.jpg
```
it sends the image correctly; i also tried to add the variable in the text (and it failed); it looks like the alarmo actions cant access home assistant variables

my workaraound is to use automations to send alarm notification instead the built in ones, but using the built in one would be more nice
