### ISSUE TITLE
changed_by information not alarmo_failed_to_arm event data

### ISSUE THREAD

**Issue by dannybloe** [nielsfaber/alarmo#676]
### Alarmo Version

1.9.7

### HA Version

2023.1

### Bug description

Alarmo nicely emits the event `alarmo_failed_to_arm` that I can use to create custom actions for (AppDaemon). However, the `changed_by` user is not in the event data:

```
event_type: alarmo_failed_to_arm
data:
  command: arm_away
  context_id: null
  area_id: "1678105150"
  reason: open_sensors
  sensors:
    - binary_sensor.raam_gym_window_door_is_open
origin: LOCAL
time_fired: "2023-03-08T14:00:41.010883+00:00"
context:
  id: 01GV0RCASJXTXQKBASDWHY4NVW
  parent_id: null
  user_id: null
```

I want to only send a notification to the actual user who is trying to arm the system with information about open windows and such (he/she is the only one at home and the only one who can close open windows, no need to send this notification to anyone else). In order to do that I need to know the changed_by information. This information is available when using Alarmo's built-in notification option (but that doesn't allow to filter for user)

### Steps to reproduce

listen to `alarmo_failed_to_arm` event using the developers tool in HA while entering a code that fails due to open windows.
