### ISSUE TITLE
Sensors: detection of device_class for binary_sensor group incorrect

### ISSUE THREAD

**Issue by mleiber** [nielsfaber/alarmo#696]
### Alarmo Version

v1.9.8

### HA Version

2022.4

### Bug description

consider following binary sensor group definition:
```
    binary_sensor:
    - platform: group
      name: verschluss_og
      device_class: opening
      entities:
      - binary_sensor.kontakt_elternbad_state
      - binary_sensor.kontakt_kinderbad_state
 ```
then the sensor list in Alarmo shows this sensor as `Tamper` instead of `Opening`
```
Fenster OG : Tamper
binary_sensor.verschluss_og
```
When looking up the sensors definition it definitely shows `Opening` as the device_class. Guess this doesn't impact the functionality but thought I report this anyhow.

### Steps to reproduce

configured as above, observed result.
