### ISSUE TITLE
alarmo/event MQTT never triggered

### ISSUE THREAD

**Issue by robertoprubio** [nielsfaber/alarmo#719]
### Alarmo Version

1.9.9

### HA Version

2023.05.1

### Bug description

MQTT alarmo/event is never triggered.
I have created an automation to respond alarmo/event (FAILED_TO_ARM or TRIGGERED events) to perform some actions (Alarmo only supports one action by event at the same time) but the alarmo/events aren't sent. 
alarmo/state events are sent but not the correspondient alarmo/event

### Steps to reproduce

Create an automation to see the events.
I attach the one I have created:

```
alias: Notificar si falla al ARMAR la alarma
description: ""
trigger:
  - platform: mqtt
    topic: alarmo/event
condition:
  - condition: template
    alias: Failed to Arm?
    value_template: "{{ event == 'FAILED_TO_ARM' }}"
action:
  - service: notify.telegram_urgente
    data:
      message: La alarma NO SE PUDO ENCENDER   {{ sensor }}
      data:
        parse_mode: html
variables:
  event: "{{ trigger.payload.event }}"
  sensor: "{{ trigger.payload.sensors[0].name }}"
mode: parallel
```
