### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by r3mcos3** [nielsfaber/alarmo#73]
I found your integration on discord, somebody was mentioning it.
it is an amazing integration, keep up the good work!

But i found a bug i think, It is not possible to turn on a script in the action part. 

![scripts](https://user-images.githubusercontent.com/45529818/102638232-77097200-4157-11eb-9107-19fe140b7c7a.jpg)

This is the yaml it's creating

```
name: Alarm Triggered
modes:
  - armed_away
triggers:
  - state: triggered
actions:
  - service: script.turn_on
    service_data:
      entity_id: script.1607170311437
```

**Comment by nielsfaber** [comment]
The problem is that a script is not turned on or turned off. It should be executed.

I should make something that changes the buttons below when you choose script.

Please give me a week or so, I will add it when I find the time.

**Comment by r3mcos3** [comment]
Thanks for your quick response, 

enjoy your Holidays days,

**Comment by zbuh** [comment]
I'm using scripts, and they work fine with turn_on

**Comment by r3mcos3** [comment]
@zbuh can you share your yaml off that action part?

**Comment by zbuh** [comment]
```
name: Alarm Triggered - Home
modes:
  - armed_home
triggers:
  - state: triggered
actions:
  - service: script.turn_on
    service_data:
      entity_id: script.alarm_triggered_home
```
