### ISSUE TITLE
Skip area for master when arm/disarm

### ISSUE THREAD

**Issue by Laxilef** [nielsfaber/alarmo#756]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Hello. Could you add the ability to exclude areas when arm/disarm for the master?
This is useful when it is necessary to disarm all areas other than bedrooms where people are currently sleeping.
For example, my configuration has lights and curtains in an area. And when the master is disarmed, the curtains open in all rooms.

Example:
```
  - service: alarmo.arm
    data:
      entity_id: alarm_control_panel.master
      code: '1234'
      mode: disarm
      skip_delay: true
      exclude:
        - Bedroom 1
        - Bedroom 2
```
