### ISSUE TITLE
Adding support for hassio.addon_stdin

### ISSUE THREAD

**Issue by wes1993** [nielsfaber/alarmo#781]
### Checklist
- [ X] I checked for similar existing requests (both open and closed) before posting.
- [X ] My request is generic, other users may benefit from it too.

### Proposal
Add support for "hassio.addon_stdin" service in Notify under Action

### Additional info
Add support for "hassio.addon_stdin", below is an example of the scritp:

```
data_template:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: sip:+393333333333@sip.vohippo.com
    message_tts: "Aarm triggered from sensors: {{open_sensors}}"
service: hassio.addon_stdin
```

Best Regards
Stefano
