### ISSUE TITLE
alarm notification target to a script

### ISSUE THREAD

**Issue by cedricbompart** [nielsfaber/alarmo#800]
Hi,

I'm trying to use your event notification to use the text-to-speech to my Sonos speaker; it works perfectly but I can't set a volume level before triggering the message.

```
service: tts.speak
data:
  message: "The alarm could not be armed right now, due to: {{open_sensors|lang=en-GB}}"
  media_player_entity_id: media_player.office
  entity_id: tts.google_en_com
```

I've played around with a Home Assistant script which set a volume level and reset the previous level after playing the message.

```
alias: test
variables:
  previous_volume: "{{ state_attr('media_player.office', 'volume_level') | float }}"
sequence:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.office
  - service: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.office
      message: hello
    target:
      entity_id: tts.google_en_com
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: media_player.volume_set
    data:
      volume_level: "{{ previous_volume }}"
    target:
      entity_id: media_player.office
icon: mdi:alarm-light-outline
mode: single
```

Would it be possible to integrate the usage of HA scripts into your notification events ? ...obviously the message needs to be dynamically set like yours.

FYI; I'm using HA 2023.9.2 and Alarmo 1.9.10.

Cheers,
