### ISSUE TITLE
Sensor cannot be selected, bug or not?

### ISSUE THREAD

**Issue by nicolazilio** [nielsfaber/alarmo#806]
### Alarmo Version

v1.9.10

### HA Version

2023.10.1

### Bug description

I put this down as a bug, but maybe I am mistaken.

I have created three, seemingly identical, sensors using the template integration:

```yaml
template:
  - trigger:
      - platform: state
        entity_id: sensor.passage_sensor_passage_counter_value_ch3
    binary_sensor:
      - name: "Passage Dining ⇾ Kitchen"
        state: true
        auto_off: 5 # s
        icon: "mdi:eye"
        unique_id: passage_sensor_dining_kitchen
        device_class: motion
  - trigger:
      - platform: state
        entity_id: sensor.passage_sensor_passage_counter_value_ch2
    binary_sensor:
      - name: "Passage Kitchen ⇾ Dining"
        state: true
        auto_off: 5 # s
        icon: "mdi:eye"
        unique_id: passage_sensor_kitchen_dining
        device_class: motion
  - trigger:
      - platform: state
        entity_id: sensor.passage_sensor_passage_counter_value_ch2
      - platform: state
        entity_id: sensor.passage_sensor_passage_counter_value_ch3
    binary_sensor:
      - name: "Passage combined"
        state: true
        auto_off: 5 # s
        icon: "mdi:eye"
        unique_id: passage_sensor_combined
        device_class: motion
```

yet I can only see/select "Passage combined" or "Passage Kitchen ⇾ Dining" in Alarmo, any ideas why? Could this be a bug?

Thanks!

### Steps to reproduce

See above
