### ISSUE TITLE
Sensor in alarmo list are change the alarm state since last update

### ISSUE THREAD

**Issue by rt400** [nielsfaber/alarmo#829]
### Alarmo Version

1.9.12

### HA Version

2023.11.0

### Bug description

I have sensors that are in ALARMO list that with Enable state.
Since the last update, any state change of a sensor that is in the list trigger this automation :
```
- id: Set_Alarm
  alias: "Set Alarm"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home_system_alarm
  condition: []
```
It's looks like that on any sensor change (OPEN / CLOSE) make change the entity "alarm_control_panel.home_system_alarm" and make the automation trigger.

### Steps to reproduce

I went back to version 1.9.10 and the problem does not exist.
