### ISSUE TITLE
YAML code not saved in Notification's task under Actions

### ISSUE THREAD

**Issue by skydado** [nielsfaber/alarmo#877]
### Alarmo Version

v1.9.13

### HA Version

latest

### Bug description

I want to increase Alexa volume before a notification and then set it back.
I see there are a lot of new feature request [here](https://github.com/nielsfaber/alarmo/issues/745) and [here](https://github.com/nielsfaber/alarmo/issues/616) and hope it will come natively.

Meanwhile I'm trying to add few lines of code in the yaml notification task editor, but I got the same problem described [here](https://github.com/nielsfaber/alarmo/issues/675): I add the code but it is not saved. Don't want to use external scripts and call them from here.

### Steps to reproduce

Go to Alarm Panel, Actions, create new notification, then in the TASK card switch to YAML 

This is the standard code coming from the UI:
```
service: notify.alexa_media_echo_dot
data:
  message: This is the message
  title: ""
```

Modify it as following:
```
`service: media_player.volume_set
metadata: {}
data:
  volume_level: 0.4
target:
  entity_id:
    - media_player.echo_dot
service: notify.alexa_media_echo_dot
data:
  message: This is the message
  title: ""`
```

If you TRY IT, the added part (that is still there in the screen) is not run.
If you return to UI or just save and go back again to see the yaml task code ... the added part disappeared.
