### ISSUE TITLE
Status pending not working as expected

### ISSUE THREAD

**Issue by daloki83** [nielsfaber/alarmo#897]
### Alarmo Version

v1.9.14

### HA Version

2024.2.2

### Bug description

Alarm away activated - Opening the door and the status should be pending for 60secs. This should trigger the below script which would play a sound (like a warining or reminder before firing the alarm). However the sound will not be played. 
After entering the correct pin code, then the sound will be played on the fire tab. 

### Steps to reproduce

```
alias: 0_Alarm_pending
description: ""
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.alarmo
    from: armed_away
    to: pending
condition: []
action:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.2
    target:
      entity_id: media_player.fire_tablet
  - repeat:
      sequence:
        - service: media_player.play_media
          target:
            entity_id: media_player.fire_tablet
          data:
            media_content_id: media-source://media_source/local/bedside-clock-alarm-95792.mp3
            media_content_type: audio/mpeg
          metadata:
            title: bedside-clock-alarm-95792.mp3
            thumbnail: null
            media_class: music
            children_media_class: null
            navigateIds:
              - {}
              - media_content_type: app
                media_content_id: media-source://media_source
      while:
        - condition: state
          entity_id: alarm_control_panel.alarmo
          state: pending
mode: single
```
