### ISSUE TITLE
Actionable notifications not working

### ISSUE THREAD

**Issue by erkr** [nielsfaber/alarmo#900]
### Alarmo Version

V1.9.14

### HA Version

2024.2.4

### Bug description

I’m new to Alamo and it looks great! Setting it up  was very easy.
Now I try to configure actionable notifications.
I guess I miss something, but the notification itself works, but the actions are missing.

This is the configuration I used;
``` 
service: notify.mobile_app_iphone_eric
data:
  message: Alarm [{{arm_mode}}] is triggered by {{open_sensors|format=short}}
  title: Alarm triggered
  data:
    actions:
      - action: ALARMO_DISARM
        title: Dis-Arm
      - action: ALARMO_ARM_AWAY
        title: Arm-Away
      - action: ALARMO_ARM_HOME
        title: Arm-Home
``` 

### Steps to reproduce
These are the settings in the UI:
![image](https://github.com/nielsfaber/alarmo/assets/4363599/3ce869a0-70ae-4415-936d-f4e88c97041a)

Press try , or trigger a sensor
