### ISSUE TITLE
Add channel to mobile notifications

### ISSUE THREAD

**Issue by mogultekin** [nielsfaber/alarmo#935]
### Checklist
- [Done] I checked for similar existing requests (both open and closed) before posting.
- [Done] My request is generic, other users may benefit from it too.

### Proposal
Please add channel to mobile notifications. In the companion app we can arrange different sounds to channels. I created a channel in the companion app as "Alarm Triggered" and changed the sound to Alarm.mp3 in my Android phone. When a message arrives to that channel Alarm.mp3 played instead of default sound of HA Companion App Notification.

https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-channels

### Additional info
I even tried adding channel in yaml in your Notification Editor but the syntax was rejected.

**Comment by golles** [comment]
It would be good if you could share what you've tried in yaml mode.

What happens when you manually trigger the notify service with the yaml in the Home Assistant Developer Options?

For me (iOS) this is working fine:
```yaml
service: notify.sander
data:
  message: "Het alarm is geactiveerd! Oorzaak: {{open_sensors|lang=nl}}."
  title: 🚨 Alarm
  data:
    url: /dashboard-status/alarm
    push:
      interruption-level: critical
      sound: alarm.caf
```
