### ISSUE TITLE
open_sensors attribute is None

### ISSUE THREAD

**Issue by PeterPalenik** [nielsfaber/alarmo#939]
### Alarmo Version

v1.10.1

### HA Version

2024.5

### Bug description

After upgrading HA from 2024.4.4 to 2024.5 my automations that trigger by alarmo zone's state changing to triggered and use the `trigger.to_state.open_sensors` attribute stopped working. When the alarm triggers, this attribute is always `None`.  It works flawlessly with older HA version - downgrading to 2024.4.4 helps.

### Steps to reproduce

- Create automation with state trigger, to: Triggered
- Trigger the alarm by one of the sensors
- Check automation's traces, where `trigger.to_state.state` is None

**Comment by nielsfaber** [comment]
I tried this just now, for me it works fine. This is the information that is available in the trace:
```yaml
   to_state:
    entity_id: alarm_control_panel.alarmo
    state: triggered
    attributes:
      code_format: null
      changed_by: Admin
      code_arm_required: false
      arm_mode: armed_home
      open_sensors:
        binary_sensor.back_door: open
        binary_sensor.frontdoor: open
      bypassed_sensors: null
      delay: null
      friendly_name: Alarmo
      supported_features: 11
```
I am using HA 2024.6.0b2.

You also say 
> Check automation's traces, where trigger.to_state.state is None

But at the same time your automation trigger is configured to fire when `to_state.state` is `triggered`.
I would expect that the `to_state` cannot be `none`, because if this was the case the automation should not be executed.

Unfortunately automations are handled by HA, including the information that is passed to the automation when triggered.
So I don't really know how to help further with this.

Is the issue still occurring for you?
