### ISSUE TITLE
Alarmo With google

### ISSUE THREAD

**Issue by awptechnologies** [nielsfaber/alarmo#967]
### Alarmo Version

 v1.10.2 

### HA Version

2024.7.0

### Bug description

After latest update of alarmo i can now arm and disarm with google. The only issue is google still says sorry i was unable to connect. Again it does actually work but for some reason google thinks it doesnt. I can deal with it just a bummer because it makes me feel like i need to check weather it worked or not everytime.

### Steps to reproduce

ask google to arm or disarm security system

**Comment by awptechnologies** [comment]
if this is only me i will deal with it. Thank you for an amazing do it yourself alarm system. by far the best.

**Comment by Baldhor** [comment]
> if this is only me i will deal with it. Thank you for an amazing do it yourself alarm system. by far the best.

Hello, I confirm you are not the only one.
Arming (no pin code) give me an error, but the alarm is still arming correctly, II'm using the following automation to compensate:
```
alias: Notif Armement Commence
description: ""
trigger:
  - platform: device
    device_id: 2692eb9f260d44f098dfce36e4928be0
    domain: alarm_control_panel
    entity_id: ff19188a9f26db85e7481704af831039
    type: arming
condition: []
action:
  - service: script.envoyer_message_vocal_sur_hub
    metadata: {}
    data:
      notif: L'alarme est armée, vous avez 30 secondes pour sortir
mode: single
```

As for disarm, I use the following automation:
```
alias: Notif Alarme Désactivée
description: ""
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.alarmo
    to: disarmed
condition: []
action:
  - service: script.envoyer_message_vocal_sur_hub
    metadata: {}
    data:
      notif: L'alarme est désactivée
mode: single
```

Yes, it's in French, I'm using my own google assistant integration to support French.
The standard integration of Google Assistant is hard coded in English ... : https://github.com/Baldhor/baldhor-google-assistant
