### ISSUE TITLE
Migrate legacy notification to new format

### ISSUE THREAD

**Issue by xhemp** [nielsfaber/alarmo#989]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.7.1

### Bug description

![0758f9bf553523e177c625406c4c826028b2a760](https://github.com/nielsfaber/alarmo/assets/13650956/5f5e8fa0-4257-4a37-8cd7-89bbdf2aad87)

(Ignore the notify.energy above, just got an example of the message which shows on HA).

I use the notification to write which sensor has been tripped and then it calls my phone using an Asterisk server.
I tried to write the notification on yaml but it doesn’t allow me to save it on Alarmo.
Am I mixing things up or is this genuine? 

This is what I have on the notify bit inside Alarmo:

```
service: notify.me_asterisk
data:
  message: "House alarm has been triggered! Cause: {{open_sensors|format=short}}."
  title: ""
```

And this is what I tried which errors out:

```
service: notify.send_message
target:
  entity_id: notify.me_asterisk
data:
  message: "House alarm has been triggered! Cause: {{open_sensors|format=short}}."
  title: ""
```

### Steps to reproduce

Just try to send a notification on Actions - Notification on Alarmo

**Comment by nielsfaber** [comment]
Do you have any link to information about this migration? I’m not aware of any recent changes in HA regarding this.

**Comment by JBlohm** [comment]
New notify entity platform
https://developers.home-assistant.io/blog/2024/04/10/new-notify-entity-platform/

**Comment by michaelblaas** [comment]
Any update on this issue? 

If I try to convert the old format to the new format (as shown by topic starter) I get an error when testing or saving:

"Actie notify/send_message kon niet worden uitgevoerd. must contain at least one of entity_id, device_id, area_id, floor_id, label_id."

**Comment by Schermbecker** [comment]
> Any update on this issue?
> 
> If I try to convert the old format to the new format (as shown by topic starter) I get an error when testing or saving:
> 
> "Actie notify/send_message kon niet worden uitgevoerd. must contain at least one of entity_id, device_id, area_id, floor_id, label_id."

Same here: I use Alarmo notifications also to notify mobile devices and if there are bypassed_sensors, I put them into these notificiations aswell. This worked pretty good but since last HA updates the IF stuff is printed into the notification.
While searching for a reason I came across the deprecated notify.send_message topic and finally landed here ;-)

This code does not work anymore (and can't be edited as required in Alarmo):

{% if bypassed_sensors | length > 0 %}
Sensors ignored: {{bypassed_sensors}}
{% endif %}

I would highly appreciate a fix for that. I by the way love Alarmo!

**Comment by nielsfaber** [comment]
I am not sure what is requested here, but I will try summarize it in my own words, hope anyone could confirm/correct me.

If I understand correctly, the migration is about replacing the 'legacy' service format:
```yaml
service: notify.<my_device_name>
data:
  ...
```

with the 'new' service format
```yaml
service: notify.send_message
target:
  entity_id: notify.<my_device_name>
data: 
  ...
```
For me, only the 'legacy' format works, the second one fails.
There are no notify entities in my configuration, but I do have some notify services available.
From this I can only conclude that the migration is not yet completed on the side of HA, at least not for the notify platforms I am using (such as mobile_app and persistent_notification).
It could be that _some_ platforms already implement the new format, but not all.
Hence the switch to the new format can also not (yet) be done from Alarmo's side.
The architecture discussion about this seems pretty much dead since May, so there doesn't seem to be any steps taken in completing the migration. 

My conclusion is that the current situation is a bit of a mixup, some integrations use the 'legacy' format, others use the 'new' format. 
From alarmo's side there is (AFAIK) no way to detect which platform uses which, so it's hard to create support for either format using the UI editor (which generates YAML underwater so should know about which format to use). 
What I could do is that user can set up the new format in the YAML editor, without getting any error message.
Which is not really an ideal situation, but at least produces a working action.

@xhemp Could you share your views on this?
